### ISSUE TITLE
Works fine with local-render, but does not generate correctly.

### ISSUE THREAD

**Issue by jcguu95** [goodroot/hugo-classic#10]
I followed the instructions and use `hugo` to generate `index.html` and other files at the end. The format did not seem right:
![pic-full-191026-1635-43](https://user-images.githubusercontent.com/35076773/67625651-c6cc0200-f80e-11e9-8771-dc6fcd5152a8.png)

However, it renders perfectly by `hugo server -w`
![pic-full-191026-1635-46](https://user-images.githubusercontent.com/35076773/67625655-d8150e80-f80e-11e9-8bda-d03d32000c98.png)

How can I make the generated one look like the same as the locally rendered one?

**Comment by goodroot** [comment]
@jcguu95 Weird! I'll take a look.

Any errors in the console when you generated?

**Comment by jcguu95** [comment]
Not of I'm aware of. I should provide the procedures I followed -- being very new to Hugo, I might have misunderstood something.

```
cd ~
mkdir website-local
cd website-local
hugo new site .

echo "# website-global" >> README.md
echo "public/" >> .gitignore
git init
git add .
git commit -m "first commit"

# Then manually replace `config.toml` by that in the theme package.

# We can now host it locally by running `$ hugo server -w` Read the
# message and go to the indicated local url. It should be rendered
# fine.

hugo new post/hello.md
cd content/post/
vim hello.md

# Manually change "draft: true" to "draft: false" for publishing and
# add content.

cd ../..
hugo -d . # this will generate the site
git add .
git commit -m "generated!"

# Then manually create a repo "website-global" in github and get its url.
git remote add origin https://github.com/jcguu95/website-global.git
git push origin master # Enter username and password

# Go to setting of the repo and change to master-branch for github page.
```

Forget about the "git" thing. I expect the procedure above should generate a good html with associating files. If that's not the case -- perhaps I missed something -- would you mind pointing it out..? I am very excited to get my hands on `hugo-classics` and make some sites with it :) Thank you!

**Comment by goodroot** [comment]
Ahh -- I see what's up.

@jcguu95 You might find this interesting: https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

Netlify is how I host my personal website. It's great! Free, very fast CDN that works well with Hugo.

The pages you've generated need to be built and served. Clicking on the HTML and expecting to see the rendered copy won't work. Give the above guide a try. 👍

**Comment by jcguu95** [comment]
Ah! I thought Hugo generates a complete site! Is this an issue just for this theme package, or it's just like this in general in Hugo?

**Comment by goodroot** [comment]
@jcguu95 It would be for any Hugo site. 😄
