### ISSUE TITLE
Wizard Image Not Loading

### ISSUE THREAD

**Issue by acse-fk4517** [goodroot/hugo-classic#11]
Hi,

First of all love this theme!

I just had an issue though. The wizard image does not seem to load on my end using the <img> tags:

```
---
title: Home
---

<img
  id="main-image"
  src="/images/partywizard.gif"
  alt="Kellen Face"/>
```

This fails to do anything.

However if directly below that block I add this line:

![Example image](/images/partywizard.gif)

This seems to work.

Any idea what is going on here?

**Comment by goodroot** [comment]
Heya!

Let's try some stuff.

1. Ensure that the partywizard.gif image is located at: `/static/images/partywizard.gif` in your own repo.
2. This simplified markup shall do: `<img src="/images/partywizard.gif">`. Does that work?

**Comment by acse-fk4517** [comment]
Thank you!

I figured it out, it is because there has been a change in the HTML renderer due to an update.

The following fixes this issue:

[https://jdhao.github.io/2019/12/29/hugo_html_not_shown/](https://jdhao.github.io/2019/12/29/hugo_html_not_shown/)

**Comment by goodroot** [comment]
Thank  you so much! I will read and see if I can make a change.
