### ISSUE TITLE
support TOC 

### ISSUE THREAD

**Issue by jiacai2050** [goodroot/hugo-classic#25]
Hi, I love this theme, thanks for sharing.

I want to migrate my blog to this theme, but find this theme don't support TOC, would you mind support this?

**Comment by nocanstillbb** [comment]
> Hi, I love this theme, thanks for sharing.
> 
> I want to migrate my blog to this theme, but find this theme don't support TOC, would you mind support this?

https://github.com/nocanstillbb/hugo-classic/commit/c026cbcfaf0b7a4674ccceb6def7d9c7b2efa009
you are welcome

**Comment by jiacai2050** [comment]
Thanks, add to my blog. Anyone interested can check this
- https://emacs.liujiacai.net/post/038-hello-treesitter/

**Comment by goodroot** [comment]
Thanks @nocanstillbb ! This is now upstream.

Blog looks great @jiacai2050 -- closing this out.
