### ISSUE TITLE
Example images, icons and emoji support not loading on initial example site (possible confusion in initial steps on my end?)

### ISSUE THREAD

**Issue by radbirb** [goodroot/hugo-classic#32]
Hello! Lovely hugo theme and personal website! I am currently somewhat struggling with the example site not seemingly rendering correctly? Unless this is intentional, I'm not sure if I've had a misstep in following your (or hugo's) instructions but on initial render, the site doesn't really look like anything from the example images.
P.S. I'm really new to Hugo and setting up websites in general, if I've done anything wrong or this is intentional, my apologies! ,:p

![image](https://github.com/goodroot/hugo-classic/assets/64087758/6233d9ce-58b2-4ed4-b8c8-76b858697570)

`hugo server` output:
```
Watching for changes in /home/rad/Projects/radiistatic/classic/{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /home/rad/Projects/radiistatic/classic/hugo.toml
Start building sites … 
hugo v0.128.2+extended linux/amd64 BuildDate=unknown


                   | EN  
-------------------+-----
  Pages            | 28  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 13  
  Processed images |  0  
  Aliases          |  0  
  Cleaned          |  0  

Built in 112 ms
Environment: "development"
Serving pages from disk
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) 
Press Ctrl+C to stop
```

I am afraid I might be missing some dependency maybe? I'm on Arch Linux/EndeavourOS and I've installed both `hugo` and `dart-sass`.

**Comment by goodroot** [comment]
Yoooo! I am very glad you appreciate it, @radbirb.

Emojis, let's do those first. Those are easy!

Add this to the `config.toml` or `hugo.toml`, whichever you are using.

```
enableEmoji = true
```

Maybe helpful. The full `toml` file used on me' personal site looks as such:

```
baseurl = "https://goodroot.ca"
enableEmoji = true
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
preserveTaxonomyNames = true
publishDir = "docs"
theme = "hugo-classic"
title = "goodroot"

footnotereturnlinkcontents = "↩"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 2

[[menu.feed]]
name = "rss"
url = "/index.xml"
weight = 1

[[menu.main]]
name = "Writing"
url = "/categories/writing/"
weight = 2

[[menu.main]]
name = "Music"
url = "/categories/songs/"
weight = 3

[[menu.feed]]
name = "GitHub"
url = "https://github.com/goodroot"

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[params]
custom_css = ["css/theme-override.css"]
description = "Thoughts from the deep."
footer = "<< Be Excellent to Each Other >>"
```

---

The images - both the FOX and the PARTYWIZARD are still there. Rockin'. Forever.

But the path is likely incorrect.

The default path is:

```
<img
  id="foxy"
  src="/images/grayf0x.jpg"
  alt="A foxy face">
```

While the default configuration is probably:

```
<img
  id="foxy"
  src="/static/images/grayf0x.jpg"
  alt="A foxy face">
```

So your `_index.md` might look like this:

```
---
title: Home
description: "The personal writings and expressions of Grayfox, otherwise known as you too and everyone else. It is a loving and silly place."
---
<img
  id="foxy"
  src="/static/images/grayf0x.jpg"
  alt="A foxy face">

## Welcome, friend

### :purple_heart: :earth_africa: :purple_heart:

Born in [The Abyss](https://en.wikipedia.org/wiki/Edmonton), **Grayfox** - also known as Zerkle Snorp - has spent over two decades fiddling with things on the Internet. Today he does nothing, so stop asking.

Their greatest joys are darkness and its quietudes.

<img src="/static/images/partywizard.gif">

---

## Musings
```

Alternatively, move the images where they are "supposed to" be: an 'images' folder, not nested inside of `static`.

---

That should do it!~

Hugo has changed their base file structure, etc, so my instructions are not correct.

I'll fix it!... Some day!... Maybe!...

**Comment by radbirb** [comment]
Ahhh!!! thank you so much, the example site works perfectly now (your config file was a massive help! (I also found out that hugo for some reason ignored `config.toml`, so I moved everything to `hugo.toml` and it started picking everything up right), I'll get to tinkering around some more but I really appreciate it! looking forward to using this for my personal site :] <3 

![image](https://github.com/goodroot/hugo-classic/assets/64087758/d0246416-7f91-498f-bbec-f91bb3e7914b)

**Comment by goodroot** [comment]
Ya! Enjoy 🖖 !

**Comment by yostwest** [comment]
Thanks! I've the same issue. ❤️
