### ISSUE TITLE
Template error on start

### ISSUE THREAD

**Issue by goodroot** [goodroot/hugo-classic#4]
https://github.com/Pac23 reports that something is exploding when he tries to run things locally. 

Image: https://imgur.com/a/tfc2flb

**Comment by goodroot** [comment]
@Pac23 Hello! I spun this up on a fresh MacOS installation to give it a try. It worked. I think the issue might be a missed step in the configuration. I have updated the README to make it more clear.

When you use `hugo new site classic` to create a new project, the `hugo-classic` repository is added to `classic/themes`. After that, the contents of the exampleSite directory need to be moved into the directory within which you created your project. This will over-write the existing files. After that, running `hugo server` should bring up the working site.

I hope this works for you!

**Comment by Pac23** [comment]
i am on Tux maybe this is causing the issue.I'll give this a try and get back.Thank you for the quick response.Great theme

**Comment by Pac23** [comment]
@goodroot still the same https://imgur.com/a/Yac7WEM

**Comment by Pac23** [comment]
Got it working,apparently it was a linux issue 

`sudo apt-get install hugo`

downloads a very old version which causes issues

using a snap package solved the issue as it had the latest version of hugo.

**Comment by goodroot** [comment]
@Pac23 Awesome! I was stumped. Enjoy the theme and have an excellent week.
