### ISSUE TITLE
Is hugo-classic support pages?

### ISSUE THREAD

**Issue by charliewin** [goodroot/hugo-classic#5]
When the posts too many, is this can split into pages, like https://themes.gohugo.io/hugo-xmag/?

**Comment by goodroot** [comment]
Sorry @charliewin ! I missed this message.

There is no pagination support built in, but you can extend it by following this guide: https://gohugo.io/templates/pagination/.

Perhaps I will get around to that in the near future. I will let you know if I do. :)
