### ISSUE TITLE
When new categories are created, it doesn't show up in categories section, but instead leads to the 404 page

### ISSUE THREAD

**Issue by msaharia** [goodroot/hugo-classic#6]
Hi, when I create new posts and add new categories, it is not added to the list of categories.

**Comment by msaharia** [comment]
Solution: Hugo needs to be restarted with `--disableFastRender` option.

**Comment by goodroot** [comment]
@msaharia I am SO late. But thank you, sir, for documenting your fix. I appreciate you and wish you good health.
