### ISSUE TITLE
Hugo warns ".Pages " is going to be deprecated

### ISSUE THREAD

**Issue by BlurryLight** [goodroot/hugo-classic#8]
My Hugo version is 
```
Hugo Static Site Generator v0.57.2/extended linux/amd64 BuildDate: 2019-08-18T05:29:32Z
```

And it throws a warning about `Pages ` is going to be deprecated in version 0.58 and recommands to use `.Site.RegularPages ` to replace it. 

So the code here needs to be updated. https://github.com/goodroot/hugo-classic/blob/36aab5e8ab906a94c8f405afb6dbea57496b9aee/layouts/_default/list.html#L10

**Comment by goodroot** [comment]
Fixed! Thanks @BlurryLight -- good lookin' out. 🎉
