### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by r1chy5** [goodroot/hugo-classic#9]
Hello, I would like to know if there is any way to hide the Blog section of the main page, I am fiddling and I do not achieve it, I think it would look great for aesthetics, I really like the theme.

**Comment by goodroot** [comment]
@r1chy5 Hey there! Yes, I have done so on my personal site: https://goodroot.ca.

In the theme, there is a file you want to edit: `layouts/_default/list.html`

It should look like so:

```
{{ partial "header.html" . }}

{{if not .IsHome }}
<h1>{{ .Title | markdownify }}</h1>
{{ end }}

{{ .Content }}

{{ partial "footer.html" . }}
```

Now the `content/_index.md` will render as the "main page".

Hope this helps!

**Comment by r1chy5** [comment]
Thank you very much, everything works as I wanted, thanks for creating the Theme.
